service: tku-client
app: tku
org: tokushun109
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: prod
  profile: tku
  region: ap-northeast-1
  environment: 
    BROWSER_BASE_URL: ${self:custom.secrets.BROWSER_BASE_URL}
    API_BASE_URL: ${self:custom.secrets.API_BASE_URL}

functions:
  nuxt:
    handler: ./deploy_config/index.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    # 本番稼働できるようになったら、コメントアウトを外す
    # provisionedConcurrency: 1

plugins:
  - serverless-apigw-binary

custom:
  secrets: ${file(./deploy_config/secrets.json)}
  apigwBinary:
    types:
      - '*/*'