[profiles.safest]
sandbox_mode     = "read-only"
approval_policy  = "on-request"

[profiles.dev]
sandbox_mode     = "workspace-write"
approval_policy  = "on-failure"

[profiles.full-auto]
sandbox_mode     = "danger-full-access"
approval_policy  = "never"
