root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
bin = "./tmp/main"
exclude_dir = ["tmp", "bin", "img"]
include_ext = ["go", "tpl", "tmpl", "html", "txt"]

[log]
time = true
