# Generated by Django 3.1.5 on 2021-01-29 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_create_product_and_accessory_category_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='材料カテゴリー名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name_plural': '材料カテゴリー',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='material_category',
            field=models.ManyToManyField(null=True, to='app.MaterialCategory', verbose_name='材料カテゴリー'),
        ),
    ]
