# Generated by Django 3.1.5 on 2021-01-31 07:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_create_sales_site_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4,
                                          editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='商品画像名')),
                ('image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name_plural': '商品画像',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='salessite',
            name='name',
            field=models.CharField(max_length=120, verbose_name='販売サイト名'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.productimage', verbose_name='商品画像'),
        ),
    ]
