# Generated by Django 3.1.5 on 2021-01-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_times_Product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '商品'},
        ),
    ]
