# Generated by Django 3.1.5 on 2021-01-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_max_length_description_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessory_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.accessorycategory', verbose_name='アクセサリーカテゴリー'),
        ),
    ]
